### ISSUE TITLE
required modules

### ISSUE THREAD

**Issue by tobybatch** [neontribe/ntdr-pas#3]
We need to ensure the remote dependencies are outlined for playbooks.

either use roles/myapp/meta/main.yml (https://docs.ansible.com/ansible/playbooks_roles.html#role-dependencies) to specify a provisioning playbook

or add a apt entry to the role:

```
- name: Install dependencies
    sudo: yes
    apt: pkg={{ item }} state=latest
    with_items:
        - python-foo
        - python-bar
```
